name: Deploy Docusaurus

on:
  push:
    branches:
      - main # 或您主分支的名称，例如 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # 指定 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 自动提供的 GitHub token
          publish_dir: ./build # 要发布的文件夹
          publish_branch: gh-pages # 要发布到的分支
